### ISSUE TITLE
ExtendedKey key selection is too slow

### ISSUE THREAD

**Issue by lduboeuf** [ubports/keyboard-component#116]
Currently, when i want to to select an extended key ( let say è in french ) , i have to long press the "e" key and wait 750ms in order to select the accent "è" which is too slow for a normal writing.
This result in often selecting the wrong key ( the default selected one is used ).

**Comment by Fuseteam** [comment]
seems related to #70

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/116

Sorry for your inconvenience.
