### ISSUE TITLE
Is that possible to implement the SWYPE feature?

### ISSUE THREAD

**Issue by Thieb67k** [ubports/keyboard-component#119]
Dear all,

There is no SWYPE keyboard available. From my user's side that could be an enhancement.
What about developpers' side? ;)

Best,

**Comment by Fuseteam** [comment]
skeyer is a work in progress i think
we can't call it swype because copyright

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/119

Sorry for your inconvenience.
