### ISSUE TITLE
Can't use traditional chinese characters with pinyin input

### ISSUE THREAD

**Issue by SwizzleMaster** [ubports/keyboard-component#12]
The OSK is missing a switch to allow users to switch between character sets while using the pinyin input method. The OSK does include a way to input traditional characters -- chewing/ZhuYin -- however zhuyin is mainly used by Taiwanese, which excludes the rest of us who need to type traditional Chinese characters. Most would be familiar with pinyin and not so much chewing/zhuyin, so it makes sense that the pinyin IME should include traditional characters.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/12

Sorry for your inconvenience.
