### ISSUE TITLE
crossbuilder: compiled files in the source directory

### ISSUE THREAD

**Issue by lduboeuf** [ubports/keyboard-component#135]
just do a `git status` in the directory after running crossbuilder

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/135

Sorry for your inconvenience.
