### ISSUE TITLE
languages.js needs updates

### ISSUE THREAD

**Issue by Flohack74** [ubports/keyboard-component#142]
The enumaration in https://github.com/ubports/keyboard-component/blame/xenial/qml/keys/languages.js needs an update to reflect all keyboards we have so far.

Maybe a better approach could be done so that all keyboards supply this string from their source, making it unnecessary to edit this file.

Also the pot file needs to be checked in with any change to this file, to make this string translatable on Weblate.

**Comment by Fuseteam** [comment]
wait not all keyboards are in languages.js? which ones are missing?

**Comment by Flohack74** [comment]
You need to find out :)

**Comment by Fuseteam** [comment]
i'm pretty sure every keyboard that gets added is added there as well hmmmm

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/142

Sorry for your inconvenience.
