### ISSUE TITLE
Keyboard not showing anymore

### ISSUE THREAD

**Issue by Vistaus** [ubports/keyboard-component#150]
After the latest keyboard update, the keyboard isn't showing anymore, meaning I can't even unlock my device. I don't have an external keyboard present at the moment.

How can I provide a debugging log or something you might need to debug this?

**Comment by Fuseteam** [comment]
latest keyboard update? the easiest logs to check would have to be `.cache/upstart/maliit-server.log` if you can ssh in you don't need to unlock your phone

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/150

Sorry for your inconvenience.
