### ISSUE TITLE
No Bangla keyboard : there is no bangla keyboard layout on Ubuntu touch.

### ISSUE THREAD

**Issue by Khalid-Miraz** [ubports/keyboard-component#157]
There is no Bangla keyboard leyout option in Ubuntu Touch to write bangla text.
In Linux Desktop we usually use "Avro" keyboard layout with ibus.
But in the Mobile(ios or android) we use "Ridmik keyboard" to write Bangla text.Ridmik has different type of keyboard layout thats are "avro"(অভ্র), "provat"(প্রভাত) , "jatio"(জাতীয়) etc

Here the link of Avro keyboard webpage : https://www.ridmik.com/

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/157

Sorry for your inconvenience.
