### ISSUE TITLE
Exiting selection mode doesn't work on first try

### ISSUE THREAD

**Issue by kugiigi** [ubports/keyboard-component#159]
### Steps to Reproduce
1. Press and hold the spacebar or swipe from the bottom
2. Double tap without lifting your finger and drag to enter selection mode and select some texts
3. Lift your finger then swipe again to select more texts
4. Double tap again.

### Expected Results
Exits selection mode

### Actual Results
Double tap doesn't exit selection mode. Second double tap exits it.

**Comment by Fuseteam** [comment]
confirmed working

**Comment by Fuseteam** [comment]
this still seems to be an issue on 03-05/2 while #158 seems fixed

**Comment by kugiigi** [comment]
Note that this isn't a regression in OTA-16. It just happens that this was also fixed with my proposed PR 😄
So I think this should be reopened but doesn't necessarily need to be fixed in OTA-16.

**Comment by Fuseteam** [comment]
pretty sure you have the ability to reopen @kugiigi :eyes:

**Comment by kugiigi** [comment]
I'm not sure if I can but I'm pretty sure I don't see the button to do it :sweat_smile:

**Comment by dobey** [comment]
This is working fine on my Nexus 4 without the newly proposed changes. How can I verify this issue?

**Comment by kugiigi** [comment]
You have to lift your finger after entering selection mode then swipe again. Lastly, double tap again to try exiting selection mode.

**Comment by Fuseteam** [comment]
so for brevity:
- double tap
- swipe
- double tap

**Comment by dobey** [comment]
Yes. That all works fine here.

**Comment by Fuseteam** [comment]
weird, that doesn't work on the e5 devel 0305, I'll test on the nexus5 when I get home

**Comment by kugiigi** [comment]
Yeah, it definitely happens on all my devices (Xperia X, Pinephone, MX4 and Nexus 5)

@dobey Are you sure you lifted your finger after entering selection mode and swiped again? Double tapping shouldn't work on first try. Or maybe you already installed my PR 😄

**Comment by dobey** [comment]
Yes, I am sure. Weird, now trying again it is indeed not working. But it was working fine yesterday. :shrug:

**Comment by Keneda-ut** [comment]
Since OTA 17 (RC) i have an issue, when using this form : https://media.interieur.gouv.fr/attestation-deplacement-derogatoire-covid-19/

On this field : 
![KB](https://user-images.githubusercontent.com/63530697/117552708-634ea180-b04d-11eb-9e93-eb4c12fdfb0d.png)

Before, i could select and set time, first hour then minutes in a row, just using the blue "swipe to move" keyboard feature (only way to set this kind of fields on Morph/Utouch), but now, if i swipe on the right to swap from hour to minutes, or the opposite, it closes keyboard instently.

And because miss swipes are easy, it closes often without even wanting to swap hours/minute.

I see only this commit that could have done something to this.
I just tested to go back to OTA 16 and it works like before.

Edit : now switched back to OTA-17 RC and issue again.

**Comment by Fuseteam** [comment]
that mode is technically meant to allow text selection, have you tried in the gray mode (also called cursor mover mode)

**Comment by Fuseteam** [comment]
just tested, it works in the regular "not blue" mode. it somewhat flaky but it doesn't immediately dismiss the keyboard

if its immediate blue in your case you can double tap to exit the blue mode

**Comment by Keneda-ut** [comment]
> just tested, it works in the regular "not blue" mode. it somewhat flaky but it doesn't immediately dismiss the keyboard
> 
> if its immediate blue in your case you can double tap to exit the blue mode

It didn't work before in "grey" mode, that's why i used blue one, and you're right now i just tested and yes it works now too in grey, but same behavior than i described, if i swap hours/minutes, it closes keyboard. 

EDIT : reverted back to OTA 16 and grey mode still allow changing time (so some previous update fixed that, morph or uTouch i can't tell), and keyboard doesn't close when swaping hours/minutes.

And to be clearer, when i talk about swaping hours/minutes, i talk about swiping with finger to right or left in the keyboard field, not in the website hour/minute field by touching it.

**Comment by kugiigi** [comment]
I can replicate your issue on my Nexus 5. But I don't think it is related to this issue. The change only concerns entering/exiting selection mode. 
My guess is it's related to this
https://gitlab.com/ubports/core/packaging/qtwebengine/-/merge_requests/4

**Comment by Keneda-ut** [comment]
Well, as i followed ubports thread https://forums.ubports.com/topic/6055/ota-17-call-for-testing-companion-post?_=1620508443094 that leads to this page https://github.com/orgs/ubports/projects/26 for reporting behavior, i only saw this issue, not the one you just gave me.
But as you're the dev, i believe you ^^

All i can tell is that it worked on OTA 16 but not anymore in OTA 17 :)

Should i post on here https://gitlab.com/ubports/core/packaging/qtwebengine/-/merge_requests/4 or there https://github.com/ubports/morph-browser/issues/468 ?

**Comment by kugiigi** [comment]
I'd say on the morph browser issue.
