### ISSUE TITLE
Some input method properties are not working in the Terminal app

### ISSUE THREAD

**Issue by kugiigi** [ubports/keyboard-component#161]
### Description
Properties like `surroundingLeft` and `surroundingRight` are always blank on the Terminal app
This issue originates from  ubports/ubuntu-touch#1157.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/161

Sorry for your inconvenience.
