### ISSUE TITLE
Input method properties are not working until cursor moves on QtWebEngine

### ISSUE THREAD

**Issue by kugiigi** [ubports/keyboard-component#162]
### Description
Input method properties such as `surroundingLeft` and `surroundingRight` are empty on `QtWebEngine`.
They will only start working once the cursor moves.
This originates from ubports/ubuntu-touch#1157

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/162

Sorry for your inconvenience.
