### ISSUE TITLE
Support one-handed and floating mode

### ISSUE THREAD

**Issue by kugiigi** [ubports/keyboard-component#174]
### Description
It would be great if there's a way to switch to one-handed mode and floating mode. This is specially useful for tablets.

**Comment by Fuseteam** [comment]
"it would be great" he says as he carefully plans his next step

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/174

Sorry for your inconvenience.
