### ISSUE TITLE
[Feature request] Allow removing erroneous entries from the autocorrection dictionary

### ISSUE THREAD

**Issue by ruedigerkupper** [ubports/keyboard-component#183]
Over time, wrong words the user mistakenly added to the autocorrection dictionary accumulate and keep being suggested as "corrected" spellings. This can be very unnerving.
Please provide a way to get rid of wrong entries ib the dictionary. Suggestion: Long-press on the suggested word (above the keyboard) could trigger a "remove this word from your dictionary" option.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/183

Sorry for your inconvenience.
