### ISSUE TITLE
add persion layout 

### ISSUE THREAD

**Issue by MohsenNz** [ubports/keyboard-component#21]
Hi. i am iranian person, how can i find persian layout or do coding for it?

**Comment by Fuseteam** [comment]
you can add new layouts under plugins
you can copy one of the existing folder and rename it as appropiate
there are four layouts files which you can edit as needed
the above 3 steps will not enable autocorrect et al
a good reference pull request is #55

**Comment by JassMan23** [comment]
@MohsenNz you might want to change the title once more from **persion** to **Persian**

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/21

Sorry for your inconvenience.
