### ISSUE TITLE
Improvements for the Italian keyboard

### ISSUE THREAD

**Issue by Flohack74** [ubports/keyboard-component#33]
_From @GI9VANNI on January 27, 2018 13:51_

Hello!
I would like to point out an improvement for the Italian keyboard.
In Italian **_there is_** is written **_c'è_** and it would be great if typing **_ce_** appeares **_c'è_** between the suggestions.
In general it should suggest the words joined by the apostrophes also writing only the letters, without typing them because they waste time.

_Copied from original issue: ubports/ubuntu-touch#452_

**Comment by GI9VANNI** [comment]
Another tip: in Italian **_is_** is written **_è_** and it would be good if typing **_e_** appeares **_è_** between the suggestions.

**Comment by Flohack74** [comment]
@sverzegnassi What you think?

**Comment by sverzegnassi** [comment]
The point made by Giovanni is valid.

I'm having a look at how overrides are [implemented in Ubuntu Keyboard](https://github.com/ubports/keyboard-component/commit/12ad6255ab981b231180a23d61638787d5c6f77e), and seems they are auto-generated from the dictionary.

My question now is why "è" and "c'è" are currently missing from the file, since they're the most common overrides in our language and they do appear in the language database.

I would also add "qual'è" -> "qual è" to the list of missing overrides, since it's one of the most [common mistakes](http://www.accademiadellacrusca.it/it/lingua-italiana/consulenza-linguistica/domande-risposte/lesatta-grafia-qual) Italian speakers usually do.

I definitely need to investigate a bit more, since changing the behavior of the generation tools might affects negatively other languages.

Also, I should check if we have some more recent Public Domain text, since the one currently in-use is from 1868. For the Austrian friends, the Austro-Hungarian Empire was just born (1867) :laughing:

**Comment by Flohack74** [comment]
I like the Empire but please update it! :)

**Comment by Aury88** [comment]
@sverzegnassi 
[here](http://it.feedbooks.com/publicdomain) a list of books in italian with PD copyright but I don't know if they are valid/complete alternative

**Comment by sverzegnassi** [comment]
Errata: the text in use for the Italian dictionary is dated 1917, and it's a translation from [Enrico Ruta](https://en.wikipedia.org/wiki/Enrico_Ruta).

@Aury88 Well picked! I definitely missed that website, thank you!

The actual text is an historical essay; that might be a problem since it's written with the formal language of the time, which is not representative of the current (informal) Italian.
I need to investigate if we can use more than a single source to build the dictionary.

In the website provided by Aury88, I found "La Coscienza di Zeno" by Italo Svevo*.
While it's not really Standard Italian (i.e. Tuscan-derived Italian), it's a first-person novel, with a more informal lexicon, which might help with extending the vocabulary. Language got further contaminations over time, so I suspect it shouldn't be a problem.

For the other issue about apostrophes, I'll try to have a look during this week.

_*sure I may be biased, as he's an author from my hometown._

**Comment by GI9VANNI** [comment]
I found _Uno, nessuno e centomila_ on the site recommended by @Aury88 

I believe that Luigi Pirandello, Nobel Prize in Literature in 1934, can be a good choice.

@sverzegnassi what do you think about it?

> For the other issue about apostrophes, I'll try to have a look during this week.

Great! We hope you can fix it :+1:

**Comment by Aury88** [comment]
@sverzegnassi  is it possible to copy/past a book after an other one in a single text file so to use more than one source and at the same time have a single source?

I would avoid historical essays...they tend to use a too much "academic" dictionary and be full of historical citations...

I find also [these books](http://www.gutenberg.org/browse/languages/it) (the same website have PD books in many other languages), but probably you all already know it

**Comment by GI9VANNI** [comment]
@sverzegnassi News about this issue?

**Comment by GI9VANNI** [comment]
News about this enhancement?
It would make it much easier to write...

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/33

Sorry for your inconvenience.
