### ISSUE TITLE
Keyboard size and position

### ISSUE THREAD

**Issue by bedna-KU** [ubports/keyboard-component#36]
I have problem with touch screen where is chars equal (picture below).
Is possible in settings add keyboard position and size?
There are several users with this problem.
┍━━━━━━┑
│...........│
│...........│   ┍━━━━━━━━━━━━━┑   
│...........│   │.....................=│
│==== │   │.....................=│
┕━━━━━━┙   ┕━━━━━━━━━━━━━┙

**Comment by cibersheep** [comment]
Hello. I don't know what is the problem. Could try to explain it in another words?

**Comment by bedna-KU** [comment]
This is a hardware problem with touch screen.

I need move or resize keyboard.

**Comment by cibersheep** [comment]
You can plug a usb or bluetooth keyboard and use it as an external keyboard.
OSK doesn't let being resized or moved at the moment

**Comment by bedna-KU** [comment]
Thx for reply. If you'll have time, please do not forget :)

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/36

Sorry for your inconvenience.
