### ISSUE TITLE
Change globe icon to Ubuntu icon

### ISSUE THREAD

**Issue by Amolith** [ubports/keyboard-component#44]
It'd be nice to change the globe icon to the Ubuntu icon, especially as it's not just for language selection.

From this:
![](http://i.imgur.com/SIU62wB.png)

To this or something similar:
![](https://i.imgur.com/uAcIEFU.png)

**Comment by NeoTheThird** [comment]
I like it! Should be pretty easy to fix, if anyone wants to feel a quick sense of accomplishment ;)

**Comment by dobey** [comment]
I'm not sure this makes sense to do. The globe icon is consistent with other platforms, so people coming over will know what it does. At the size it's displayed at, the "ubuntu logo" is mostly indiscernible, and it looks more like a triangle inside a circle. Most people won't recognize this is to be the means to change keyboard layout. It also doesn't match physical keyboards, where the Ubuntu key would end up being Super modifier, rather than a popup to select layout or emoji.

**Comment by gaycomputers** [comment]
Thinking about doing this as first project, what about an ubuntu icon with a small gear in corner

**Comment by cibersheep** [comment]
Mmmm... I agree with dobey, the ubuntu icon is to me a «super key» or shortcut to home.
Even the icon is not only to change language layouts, as we add emojis there, is primary to change language layouts with the exception of emojis. So, it make sense.
But, if you find a better icon for «layout» I would love to see it, obviously

https://thenounproject.com/search/?q=key%20keyboard

**Comment by cibersheep** [comment]
Also, I found this kind of _mergeable_ with #13

**Comment by UniversalSuperBox** [comment]
Closing as "wontfix" from discussion here. The general feeling seems to be that an Ubuntu icon would be inappropriate for this button, as it does not act as a "Super" key like the icon implies.
