### ISSUE TITLE
Number keyboard not showing a comma for locales that use it as a decimal separator

### ISSUE THREAD

**Issue by bhdouglass** [ubports/keyboard-component#53]
For languages that use a comma for the decimal separator (as opposed to the dot) it does not show on the number keyboard. Tested with the Spanish and Catalan keyboards on the MX4 & the Nexus 5 both on the devel channel.

**Comment by bhdouglass** [comment]
The calculator app uses `Qt.locale().decimalPoint` to show the correct separator, this should be pretty easy to add to the keyboard as each keyboard is just a qml file.

**Comment by cibersheep** [comment]
In my locale, should be `,`
![imatge](https://user-images.githubusercontent.com/6640041/49450465-56bf2280-f7dd-11e8-87ff-e8ca546e1393.png)

**Comment by Danfro** [comment]
To solve this issue a change wants to be applied to `/qml/languages/Keyboard_numbers.qml.`
Because I am not able to build keyboard component with crossbuilder by myself ( #59 ) I can not provide a tested solution. But I do have two approaches that someone else maybe can test. I tried them with a pure qml file and qml viewer, both worked there.

_1. approach:_
change line 74 from
`CharKey { label: "."; noMagnifier: true; width: c1.numKeyWidth; height: c1.numKeyHeight; }`
to
`CharKey { label: Qt.locale(Qt.locale().name).decimalPoint; noMagnifier: true; width: c1.numKeyWidth; height: c1.numKeyHeight; }`

_2. approach:_
in line 35 add this line of code
`property string decimal: Qt.locale().decimalPoint;`
and then change line 74 from
`CharKey { label: "."; noMagnifier: true; width: c1.numKeyWidth; height: c1.numKeyHeight; }`
to
`CharKey { label: c1.decimal; noMagnifier: true; width: c1.numKeyWidth; height: c1.numKeyHeight; }`

**Comment by bhdouglass** [comment]
Have you tried just editing the qml files directly on the device?

**Comment by Fuseteam** [comment]
i have tried the second approach directly on the device. i did not seem to make a difference....at least on the places i have tested

**Comment by UniversalSuperBox** [comment]
If it was going to make a difference, maliit would need to be restarted. Was that done?

**Comment by Fuseteam** [comment]
yes it was done iirc
also verified by the countless keyboard restarts i've done since :p

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/53

Sorry for your inconvenience.
