### ISSUE TITLE
Add the ability to choose your own keyboard  background image.

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ubports/keyboard-component#56]
On android, the default keyboard allows people to change they keyboards colours, but also lets you replace the colours with a background, it would be nice if you could have your own background on ubuntu touch's keyboard.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/56

Sorry for your inconvenience.
