### ISSUE TITLE
feature request: set long press time

### ISSUE THREAD

**Issue by dieharddan** [ubports/keyboard-component#70]
It would be great if we had the option to set the time in which the secondary keys pop up with a long press of a button. I guess I type fast and the current setting really slows me down.

**Comment by giiba** [comment]
Easy to change, in:
/usr/share/maliit/plugins/com/ubuntu/keys/PressArea.qml

ln:101 (I think) under 'holdTimer'

default is 300 (ms I assume) and I find 200 is much nicer. Adding the settings option would be nice.

**Comment by dieharddan** [comment]
excellent, thanks

**Comment by dieharddan** [comment]
I did change these manually which worked, but it doesn't seem to work for keys "q" and "a"; Also, when you push the "?123" button, keys "1" and " * " can be long pressed even though there's no secondary character available. This is using a op3t on edge 107.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/70

Sorry for your inconvenience.
