### ISSUE TITLE
ubuntu-keyboard-autopilot depends on libautopilot-qt

### ISSUE THREAD

**Issue by hummlbach** [ubports/keyboard-component#73]
In order to resurrect autopilot tests for the apps (calendar app for example) we need an installable `ubuntu-keyboard-autopilot` package.
But atm `ubuntu-keyboard-autopilot` depends on `libautopilot-qt` which depends on `autopilot-qt5` and `autopilot-qt4`. The latter is causing dependency issues and the further says it would replace `libautopilot-qt`. Michael Zanetti confirmed that depending on `autopilot-qt5` instead of `libautopilot-qt` seemed to be the right move.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/73

Sorry for your inconvenience.
