### ISSUE TITLE
Improve layout/language switching performance

### ISSUE THREAD

**Issue by kugiigi** [ubports/keyboard-component#79]
### Description
Currently the layouts/languages are loaded on-demand via a single Loader. This means that the layouts are loaded every time you switch to them. To make it worse, the Loader does not use asynchronous loading. Perhaps this can be improved so that switching layout will feel faster and smoother.

**Comment by Fuseteam** [comment]
interesting enough it also loads slower on the actual layouts vs languages

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/79

Sorry for your inconvenience.
