### ISSUE TITLE
Switch correction language while maintaining keyboard layout 

### ISSUE THREAD

**Issue by utyr** [ubports/keyboard-component#83]
- Device: LGE Nexus 5
- Channel: Ubuntu Touch 15.04 (r3)
- Build: (no idea, sorry!)

### Steps to reproduce
1. open messages app
2. start writing a message (eg: in German)
3. switch language to English (let's say you need the word "cool" in English, but your message is basically written in German)
4. "cool" is recognized in English, but unfortunately the keyboard layout changes -> this makes it unusual to find the letters (in my case 'y' and 'z' switch places, but my mind and fingers are used to have them where they usually are -> QWERTZ layout)

### Expected behavior
Eg: using the messages app, it should be possible to change the language and keep the keyboard layout the same. Keyboard layout and language should not be fixed to one another.

### Actual behavior
Eg: using the messages app, you can switch language (for auto-correction feature), but the keyboard layout also changes.

**Comment by UniversalSuperBox** [comment]
@utyr, I've transferred this issue to the keyboard repository. This may help it get the attention it needs.

**Comment by Fuseteam** [comment]
Should this be solved by adding a qwertz english layout?

**Comment by utyr** [comment]
the language selection helps to spell things correctly. the keyboard layout should not be connected to the language selection.
Example: I write in English, French, German, Spanish, Italian. I am used to a qwertz keyboard. So switching language should not change the letter placing (keyboard layout) because that would make me much slower when typing. 
Suggested solution: make language switch independent of keyboard layout.

**Comment by dobey** [comment]
Really, it needs to behave the same as it does in Android, where spell checking supports all active layout languages, regardless of which layout is active.

**Comment by JassMan23** [comment]
@dobey Except that can lead to the spell checker saying that something is spelt correctly when in fact the user may have mispelt a word where the incorrect spelling is a homonym of a word in a different language and which has a completely different meaning.    
The control panel group is called **Language & Text** and contains separate settings for **display language** and **keyboard layout** so surely the answer is simply to make the OSK button which selects layout also allow you select display language separately. The easieest way to do this may be to modify the longpress popup have 2 checkboxes for each selectable language. One for layout the other for display language.   
Can I suggest that the **Settings...** link on the popup  is changed to the standard **⚙** and moved to the top at the same time? This may make the need for the above mentioned second checkbox go away and also make it easier to turn the spellcheck on/off etc.

**Comment by Fuseteam** [comment]
Technically the easiest is to make a english qwertz layout
that way the user can select german and english (qwertz) effectively achieving the same end result

**Comment by JassMan23** [comment]
@fuseteam, maybe it is the easiest way technically for a one off case but surely there is a lot of effort involved in having a every possible keyboard layout for every possible language. It is also likely to lead to bloatware.  Admittedly any other solution as described below looks like this may require a change to maalit itself as a quick glance at the ubuntu specific parts of the keyboard look like the language change api is a single call which affects both layout and display language. However, I presume since maalit is also involved in other keyboards such as  numeric only, it must be possible to call the layout change separately from a language change.   

  
I have had a rethink about my previous above comment and am now of the opinion that a better solution may be to have a tabbed language popup.   
The first tab **[Language]** would be the exisiting selector list minus "settings"   
The second tab **[Keyboard]** would be visually similar but select the only layout and thus not affect the spellcheck. .   
The third tab **[ ⚙ ]** contains the original link to **system settings** but also has a checkbox  "layout follows language". This would default to unchecked because the keyboard is more likely to remain fixed for use cases as originally requested. i.e. more non-English want to write English using their own accented keyboard than "English" users want to write in a foreign language. This tab may also be a means to allow users to easily select between the 16key flick keyboard and the full keyboard.

**Comment by Fuseteam** [comment]
@JassMan23 i get where you're coming from but you're only thinking about the front end
the problem is currently language selection _is_ layout selection if want to know why i say that you can check the plugins folder
to do it "properly" will probably require a complete rearchitecture of how layouts work afaict

**Comment by JassMan23** [comment]
@Fuseteam sorry but I don't see what individual layout plugins have to do with the current issue. ALL layouts use the [LanguageKey](https://github.com/ubports/keyboard-component/blob/xenial/qml/keys/LanguageMenu.qml) to change language which changes the layout at the same time.  As I understand it, all @utyr is asking for is the ability to change the hunspell language which I presume (from looking at [.../plugins/westernsupport/spellchecker.cpp](https://github.com/ubports/keyboard-component/blob/xenial/plugins/westernsupport/spellchecker.cpp) )will also change auto-correct. As I  implied earlier, LanguageKey.qml currently either switches between the last 2 selected layouts or calls up LanguageMenu.qml.   
LanguageMenu could be modified to provide a tabbed popup. LanguageKey could check the state of the "follow" checkbox and if `<follow>`, then perform usual action. If `<not-follow>`, call SpellChecker::setLanguage(const QString &language) to change the language without changing the layout.

**Comment by Fuseteam** [comment]
actually technically the languagekey changes the layout not the language afaict
in other words it changes the layout which happens to change the language aswell
if look at the individual "layout" plugins you'll see that the language database used by hunspell are in there as well so as far as i can tell it changes the folder from where it loads the layout 
the language menu your referring to is actually a layout menu
this is how i believe it currently works
that said if you still feel that it is doable; feel free to try it
when you submit a pr it will trigger a automated build
after it finishes you should be able to install it on your phone by following the instructions in the readme
i myself did not know how this all works until i started hacking a layout

**Comment by JassMan23** [comment]
Sorry but I am almost a total noob at programming. I can see how all the various bits work but I currently don't feel feel confident enough to hack the keyboard again. I had a go once before and I think I left out a comma somewhere and almost bricked my phone. I had to run recovery.

**Comment by Fuseteam** [comment]
i really doubt that you were that close to bricking
what i suspect you mean is that the keyboard was unusable
it's usefull to have ssh acces in those cases
there's a command to restore your rootfs aswell
a good rule of thumb is to always back up

**Comment by dobey** [comment]
@Fuseteam "More layouts" is definitely not the solution to this problem, I think. :)

**Comment by Fuseteam** [comment]
@dobey i suppose not :p yet anything more will take a rearchitecture afaict :p

**Comment by Fuseteam** [comment]
ok uhh now that i've delved a bit deeper it appears there is at least on language independent layout: the symbol layout
perhaps we could morph the symshiftkey into a layoutswitchkey in order to separate language from layout

**Comment by utyr** [comment]
Fantastic! Exactly what I imagined!

Maybe I need to be more precise...
How about being able to set a keyboard layout for each chosen language? That seems even better to me. If I were used to type French with a French keyboard (say AZERTY) and German with a Swiss German keyboard (QWERTZ), then I would, when switching language, automatically get the keyboard layout I am used to. Would make sense, no? And I would be free to choose my desired keyboard layout associated to the language...

**Comment by Fuseteam** [comment]
it is? cool

**Comment by JassMan23** [comment]
Is there no way to merge the code from that layout into the menu which pops up on long press of layout selection key? I would envisage that the menu could have 2 check boxes instead of 1 per language offered. 1 for layout, the second for spellcheck/dictionary which would call the newly discovered code.

**Comment by Fuseteam** [comment]
there's no need afaict
for now the symbolshiftkey already switches between two layouts
so extending its functionality to switch between multiple layouts or perhaps a simple menu under settings to set the desired layout would suffice
imo the language key should not effect the layout

**Comment by JassMan23** [comment]
Que?
On all my devices the language key (the one with the world symbol) switches from QWERT to AZERT on a short press and brings up a menu on a long press which allows selection    
English
French
Emoji
Settings

with a checkbox on each of the 1st three 
the currently selected checkbox is always the last used of the 3 layouts  (or more if they been installed) and will become the alt layout (short press) if you check a new selection. IMHO this is where users would expect to find anything to do with locale rather than on a symbol shift key. At the moment lc_lang is following keymap, all we are discussing is a mechanism to separate the selection scheme. Sort of GUI localectl.

**Comment by Fuseteam** [comment]
as of right now the language key switching between languages which means each new layout is treated as a language which is not really that good as it means that you'll need to duplicate a lot of things just to have a new layout even if you just want to change the layout and not the language or vice versa

in addition adding to the complexity of the language key doesn't sound too appealing to me as it does what it should; loop through languages
what surprised me is that all the symbol shift key does is change the layout, as in it reuses the same layout for symbol for all languages. so in reality the symbol shift key is actually a layout switch key in disguise.
imo layout and languages should be separated how de a layoutswitch key could be implemented is a different discussion however.... perhaps such key is not even neccesary and a simple tap and hold>settings to change layout is an option as well

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/83

Sorry for your inconvenience.
