### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by tallero** [ubports/keyboard-component#88]
# How to test?

As I read on #86 I can give

    sudo ubports-qa install PR-X

to rebuild and reinstall on device the packages involved in the PR no. `X`.

This is really cool and also very practical (if it not [breaks the system over time](https://github.com/ubports/keyboard-component/pull/90#issuecomment-525808549)? I suppose one should anyway develop in a VM?)

# Logs

Where are logs being saved?

    journalctl /usr/bin/maliit-server -f -o cat

does not output anything.

EDIT: found them

**Comment by dobey** [comment]
> to rebuild and reinstall on device the packages involved in the PR no. `X`.

`ubports-qa` does not _rebuild_ changes from a PR. It simply adds the apt repository, and tries to upgrade. It needs some work to avoid mucking with apt or upgrading, so that it only downloads and installs the relevant debs for the PR/branch, still.

> journalctl

systemd is not being used on Ubuntu Touch.

**Comment by tallero** [comment]
>It needs some work to avoid mucking with apt or upgrading, so that it only downloads and installs the relevant debs for the PR/branch, still.

I noticed that. The repo should contain the build of the PR-X for all packages which did reach it, right?

Would it better to just mention that CI builds for a given PR are made available at

    https://ci.ubports.com/blue/organizations/jenkins/<project>/detail/PR-X/<build_number>/artifacts

?

>systemd is not being used on Ubuntu Touch.

I knew it uses upstart but I thought it could be used by something since it found it preinstalled.

**Comment by dobey** [comment]
> I noticed that. The repo should contain the build of the PR-X for all packages which did reach it, right?

If there are unrelated PRs on different repos, that happened to end up with the same ID, which are built by UBports CI, then they will all be in the same apt repo. This is rarely hit, but still can be a problem. As `ubports-qa` also just runs `apt-get upgrade` after adding the new repo, packages from other apt sources may also be upgraded at the same time. This is of course problematic, because it can break, and you aren't testing only the thing from the one PR you're interested in.

> Would it better to just mention that CI builds for a given PR are made available at

It'd probably be better to just fix the scripts, so that it works better and doesn't have potential to break the system, and not use apt. But it's somewhat low priority at the moment.

> I knew it uses upstart but I thought it could be used by something since it found it preinstalled.

While systemd is installed, as 16.04 switched to it as default for system level services, it is not really used on Ubuntu Touch, so `systemctl` and `journalctl` will not work. It just starts enough at boot to get the upstart shim running, and then hands things over.

**Comment by Fuseteam** [comment]
I believe this is resolved?

**Comment by UniversalSuperBox** [comment]
Closed by https://github.com/ubports/keyboard-component/pull/89
