### ISSUE TITLE
Add sensitivity adjustment for text selection/cursor movement modes

### ISSUE THREAD

**Issue by giiba** [ubports/keyboard-component#99]
When moving the cursor or selecting text with the respective mode I find I always overshoot my target and then move the cursor back and forth a few times before I can get the cursor in the intended spot.

It would be really nice if the sensitivity could be turned down (or up for some I suppose) a bit. My fat clumsy fingers could use the help.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-keyboard/-/issues/99

Sorry for your inconvenience.
